config/routes.rb
Rails.application.routes.draw do
  
  resources :baskets
  resources :presents
  resources :recipients

  root 'static_pages#index'

end

app/models/basket.rb
class Basket < ActiveRecord::Base
  belongs_to :recipient
  belongs_to :present
end

app/models/present.rb
class Present < ActiveRecord::Base
  has_many :baskets
  has_many :recipients, :through => :baskets
end

app/models/recipient.rb
class Recipient < ActiveRecord::Base
  has_many :baskets
  has_many :presents, :through => :baskets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  def create
    @basket = Basket.baskets.build(:present_id => params[:present_id])
    if @basket.save
      flash[:notice] = "Added present."
      redirect_to root_url
    else
      flash[:error] = "Unable to add present."
      redirect_to root_url
    end
  end

  def destroy
    @basket.destroy
    respond_to do |format|
      format.html { redirect_to baskets_url, notice: 'Basket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
end

app/controllers/presents_controller.rb
class PresentsController < ApplicationController
  before_action :set_present, only: [:show, :edit, :update, :destroy]
  before_action :load_recipients, only: [:new, :edit]


  # GET /presents
  # GET /presents.json
  def index
    @presents = Present.all
    @recipients = Recipient.all
  end

  # GET /presents/1
  # GET /presents/1.json
  def show
  end

  # GET /presents/new
  def new
    @present = Present.new({:present => "Toy"})
    @recipient = Recipient.new

  end

  # GET /presents/1/edit
  def edit
  end

  # POST /presents
  # POST /presents.json
  def create
    @present = Present.new(present_params)
    @recipient = Recipient.new
    respond_to do |format|
      if @present.save
        format.html { redirect_to @present, notice: 'Present was successfully created.' }
        format.json { render :show, status: :created, location: @present }
      else
        format.html { render :new }
        format.json { render json: @present.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /presents/1
  # PATCH/PUT /presents/1.json
  def update
    respond_to do |format|
      if @present.update(present_params)
        format.html { redirect_to @present, notice: 'Present was successfully updated.' }
        format.json { render :show, status: :ok, location: @present }
      else
        format.html { render :edit }
        format.json { render json: @present.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /presents/1
  # DELETE /presents/1.json
  def destroy
    @present.destroy
    respond_to do |format|
      format.html { redirect_to presents_url, notice: 'Present was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_present
      @present = Present.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def present_params
      params.require(:present).permit(:present, :cost, :recipient_ids => [])
    end

    def load_recipients
      @recipients = Recipient.all
    end
end

app/controllers/recipients_controller.rb
class RecipientsController < ApplicationController
  before_action :set_recipient, only: [:show, :edit, :update, :destroy]
  before_action :load_presents, only: [:new, :edit]

  # GET /recipients
  # GET /recipients.json
  def index
    @recipients = Recipient.all
  end

  # GET /recipients/1
  # GET /recipients/1.json
  def show
  end

  # GET /recipients/new
  def new
    @recipient = Recipient.new({:first_name => "Kirk"})
    @present = Present.new
  end

  # GET /recipients/1/edit
  def edit
  end

  # POST /recipients
  # POST /recipients.json
  def create
    @recipient = Recipient.new(recipient_params)
    @present = Present.new
    respond_to do |format|
      if @recipient.save && @present.save
        format.html { redirect_to @recipient, notice: 'Recipient and present was successfully created.' }
        format.json { render :show, status: :created, location: @recipient }
      else
        format.html { render :new }
        format.json { render json: @recipient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipients/1
  # PATCH/PUT /recipients/1.json
  def update
    respond_to do |format|
      if @recipient.update(recipient_params)
        format.html { redirect_to @recipient, notice: 'Recipient was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipient }
      else
        format.html { render :edit }
        format.json { render json: @recipient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipients/1
  # DELETE /recipients/1.json
  def destroy
    @recipient.destroy
    @present.destroy
    respond_to do |format|
      format.html { redirect_to recipients_url, notice: 'Recipient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipient
      @recipient = Recipient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipient_params
      params.require(:recipient).permit(:first_name, :present_ids => [])
    end

    def load_presents
      @presents = Present.all
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @recipients = Recipient.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/baskets_helper.rb
module BasketsHelper
end

app/helpers/presents_helper.rb
module PresentsHelper
end

app/helpers/recipients_helper.rb
module RecipientsHelper
end

app/views/baskets/_form.html.erb
<%= form_for(@basket) do |f| %>
  <% if @basket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@basket.errors.count, "error") %> prohibited this basket from being saved:</h2>

      <ul>
      <% @basket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :create %><br>
    <%= f.text_field :create %>
  </div>
  <div class="field">
    <%= f.label :destroy %><br>
    <%= f.text_field :destroy %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/baskets/edit.html.erb
<h1>Editing Basket</h1>

<%= render 'form' %>

<%= link_to 'Show', @basket %> |
<%= link_to 'Back', baskets_path %>

app/views/baskets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Baskets</h1>

<table>
  <thead>
    <tr>
      <th>Create</th>
      <th>Destroy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @baskets.each do |basket| %>
      <tr>
        <td><%= basket.create %></td>
        <td><%= basket.destroy %></td>
        <td><%= link_to 'Show', basket %></td>
        <td><%= link_to 'Edit', edit_basket_path(basket) %></td>
        <td><%= link_to 'Destroy', basket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Basket', new_basket_path %>

app/views/baskets/new.html.erb
<h1>New Basket</h1>

<%= render 'form' %>

<%= link_to 'Back', baskets_path %>

app/views/baskets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Create:</strong>
  <%= @basket.create %>
</p>

<p>
  <strong>Destroy:</strong>
  <%= @basket.destroy %>
</p>

<%= link_to 'Edit', edit_basket_path(@basket) %> |
<%= link_to 'Back', baskets_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pressie4</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/presents/_form.html.erb
<%= form_for(@present) do |f| %>
  <% @recipients.each do |recipient| %>
    <%= recipient.first_name %>
  <% end %>

  <% @recipients.each do |recipient| %>
    <div>
      <%= check_box_tag "post[recipient_ids][]", recipient.id %>
      <%= recipient.first_name %>
    </div>
  <% end %>

  <div class="field">
    <%= fields_for @recipient do |fp| %>
      <%=fp.label :recipient %><br>
      <%=fp.text_field :recipient %>
    <% end %>
  </div>



  <div class="field">
    <%= f.label :present %><br>
    <%= f.text_field :present %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.text_field :cost %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/presents/edit.html.erb
<h1>Editing Present</h1>

<%= render 'form' %>

<%= link_to 'Show', @present %> |
<%= link_to 'Back', presents_path %>

app/views/presents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Presents</h1>

<table>
  <thead>
    <tr>
      <th>Present</th>
      <th>Cost</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @presents.each do |present| %>
      <tr>
        <td><%= present.present %></td>
        <td><%= present.cost %></td>
        <td><%= link_to 'Show', present %></td>
        <td><%= link_to 'Edit', edit_present_path(present) %></td>
        <td><%= link_to 'Destroy', present, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add New Present', new_present_path %>

app/views/presents/new.html.erb
<h1>New Present</h1>

<%= render 'form' %>

<%= link_to 'Back', presents_path %>

app/views/presents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Present:</strong>
  <%= @present.present %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @present.cost %>
</p>

<%= link_to 'Edit', edit_present_path(@present) %> |
<%= link_to 'Back', presents_path %>

<p>
<%= @present.present %>
  Recipients:
  <ul>
    <% @present.recipients.each do |recipient| %>
      <li><%= recipient.first_name %></li>
    <% end %>
  </ul>
</p>

app/views/recipients/_form.html.erb
<%= form_for(@recipient) do |f| %>


  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>

  <%= f.fields_for :presents do |builder| %>
    <fieldset>
      <%= builder.label :presents, "Present" %><br />
      <%= builder.text_area :presents %> 
      <%= builder.check_box :_destroy %> 
      <%= builder.label :_destroy, "Remove Present" %>
    </fieldset>
  <% end %>

  <div class="field">
    <%= fields_for @present do |fp| %>
      <%=fp.label :present %><br>
      <%=fp.text_field :present %>
    <% end %>
  </div>

  <% @presents.each do |present| %>
    <div>
      <%= check_box_tag "post[present_ids][]", present.id %>
      <%= present.present %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipients/edit.html.erb
<h1>Editing Recipient</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipient %> |
<%= link_to 'Back', recipients_path %>

app/views/recipients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Recipients</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipients.each do |recipient| %>
      <tr>
        <td><%= recipient.first_name %></td>
        <td><%= link_to 'Show', recipient %></td>
        <td><%= link_to 'Edit', edit_recipient_path(recipient) %></td>
        <td><%= link_to 'Destroy', recipient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipient', new_recipient_path %>


<% "Recipient List" %>

<div id="recipients">
<% for recipient in @recipients %>
  <div class="recipent">
    <p>
      <strong><%=h recipient.first_name %></strong>
      <%= link_to "Add Present", baskets_path(:present_id => recipient), :method => :post %>
      <div class="clear"></div>
    </p>
  </div>
<% end %>
</div>

app/views/recipients/new.html.erb
<h1>New Recipient</h1>

<%= render 'form' %>

<%= link_to 'Back', recipients_path %>

app/views/recipients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @recipient.first_name %>
</p>

<%= link_to 'Edit', edit_recipient_path(@recipient) %> |
<%= link_to 'Back', recipients_path %> |
<%= link_to 'Add New Present', new_present_path %>


<h2>Presents</h2>
<ul>
  <% for basket in @recipient.baskets %>
    <li><%=h basket.present %></li>
  <% end %>
</ul>

<p>
<%= @recipient.first_name %>
  Presents:
  <ul>
    <% @recipient.presents.each do |present| %>
      <li><%= present.presents %></li>
    <% end %>
  </ul>
</p>

app/views/static_pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipients</h1>

<table>
  <tbody>
    <% @recipients.each do |recipient| %>
      <tr>
        <td><%= link_to recipient.first_name, recipient %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipient', new_recipient_path %>